version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/test
hooks:
  BeforeInstall:
    - location: MultipleFiles/install_dependencies
      timeout: 180
      runas: ubuntu
    - location: MultipleFiles/start_server
      timeout: 180
      runas: ubuntu
  ApplicationStop:
    - location: MultipleFiles/stop_server
      timeout: 180
      runas: ubuntu
