version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/test
hooks:
  BeforeInstall:
    - location: ./script1.sh
    - runas: ubuntu

  AfterInstall:
    - location: ./script2.sh
      timeout: 180
      runas: ubuntu
